codecov:
  codecov:
  token: a273abcd-81dc-4635-beaa-e88920d9d9c7
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, sunburst"
  behavior: default
  require_changes: no
